name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Download NLTK data
        run: python -c "import nltk; [nltk.download(r) for r in ['punkt', 'punkt_tab', 'stopwords']]"
      - name: Run tests
        run: pytest
